package cc.cyberdark.consolecoatcraft.tests;

import static org.junit.Assert.*;
import org.junit.Test;

import cc.cyberdark.flags.CoatOfArms;

public class CoatOfArmsTest {

	/**
	 * Test to ensure that the generate() method of CoatOfArms returns a non-null
	 * result.
	 * 
	 * This test creates a new instance of CoatOfArms with specific parameters and
	 * then calls the generate() method. It verifies that the result is not null,
	 * indicating that the generation process was successful.
	 */
	@Test
	public void testGenerateReturnsNotNull() {
		CoatOfArms coatOfArms = new CoatOfArms(16, "dolphin", "black", "center", "middle");

		String[] result = coatOfArms.generate();

		assertNotNull(result);
	}

	/**
	 * Test to ensure that the length of the result array generated by CoatOfArms is
	 * 16.
	 * 
	 * This test creates a new instance of CoatOfArms with specific parameters and
	 * then calls the generate() method. It verifies that the length of the result
	 * array is 16.
	 */
	@Test
	public void testGenerateResultLengthIs16() {
		// Arrange: Create an instance of CoatOfArms with specific parameters
		CoatOfArms coatOfArms = new CoatOfArms(16, "dolphin", "black", "center", "middle");

		// Act: Call the generate() method
		String[] result = coatOfArms.generate();

		// Assert: Verify that the length of the result array is 16
		assertEquals(16, result.length);
	}
}
